worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;
    
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Cấu trúc Log nhận dạng IP thực từ Cloudflare
    log_format detailed '$remote_addr - $http_cf_connecting_ip [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent" '
                        '$request_time $upstream_response_time '
                        '$http_cf_ipcountry $http_cf_ray';

    access_log /var/log/nginx/access.log detailed;
    error_log /var/log/nginx/error.log warn;

    # Limit Rate Zone (Chống DDoS / Spam / Brute force cơ bản)
    # Lấy client IP từ CF-Connecting-IP header của Cloudflare dội về
    map $http_cf_connecting_ip $client_ip {
        default $remote_addr;
        ~^.+ $http_cf_connecting_ip;
    }

    # Zone cho toàn trang, giới hạn 60 requests / giây / IP
    limit_req_zone $client_ip zone=general:10m rate=60r/s;
    # Zone cho GraphQL API, giới hạn chặt chẽ hơn: 30 requests / giây / IP
    limit_req_zone $client_ip zone=api:10m rate=30r/s;

    # GZIP Optimization
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    include /etc/nginx/conf.d/*.conf;
}
